const data = [
  {
    id: "A001",
    title: "Ergonomic Mechanical Keyboard",
    image: "keyboard_mech.jpg",
    discount: "10%",
    Price: 89.99,
    totalPrice: 80.99,
    rating: 4.7,
  },
  {
    id: "B045",
    title: "Noise-Cancelling Headphones Pro",
    image: "headphones_nc.png",
    discount: "25%",
    Price: 249.0,
    totalPrice: 186.75,
    rating: 4.5,
  },
  {
    id: "C120",
    title: "Stainless Steel Water Bottle (1L)",
    image: "water_bottle.jpg",
    discount: "",
    Price: 25.5,
    totalPrice: 25.5,
    rating: 4.9,
  },
  {
    id: "D007",
    title: "Portable SSD 1TB (USB 3.1)",
    image: "ssd_portable.webp",
    discount: "5%",
    Price: 119.99,
    totalPrice: 113.99,
    rating: 4.6,
  },
  {
    id: "E901",
    title: "4K Smart LED TV (55 Inch)",
    image: "tv_55inch.png",
    discount: "30%",
    Price: 799.0,
    totalPrice: 559.3,
    rating: 4.8,
  },
  {
    id: "F555",
    title: "High-Performance Blender",
    image: "blender_hp.jpg",
    discount: "",
    Price: 145.0,
    totalPrice: 145.0,
    rating: 4.4,
  },
  {
    id: "G311",
    title: "Yoga Mat Deluxe (Non-Slip)",
    image: "yoga_mat.jpeg",
    discount: "15%",
    Price: 39.95,
    totalPrice: 33.96,
    rating: 4.3,
  },
  {
    id: "H202",
    title: "Wireless Charging Pad",
    image: "charger_wireless.webp",
    discount: "",
    Price: 19.99,
    totalPrice: 19.99,
    rating: 4.2,
  },
  {
    id: "I777",
    title: "Digital Instant Camera",
    image: "camera_instant.png",
    discount: "20%",
    Price: 99.0,
    totalPrice: 79.2,
    rating: 4.6,
  },
  {
    id: "J808",
    title: "Subscription Box - Coffee Lovers",
    image: "coffee_box.jpg",
    discount: "",
    Price: 45.0,
    totalPrice: 45.0,
    rating: 5.0,
  },
];
export default data;
